### ISSUE TITLE
Nornir some errors.

### ISSUE THREAD

**Issue by hrtrd** [rickdonato/nornir-napalm-netbox-demo#1]
Napalm receives and displays data from devices to the console. Nornir got some errors
 2019-11-18 15:17:39,999 - nornir.core.task -    ERROR -      start() - Host 'Pirog17-dr1': task 'Create Netbox Interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/neoll/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "scripts/create_interfaces.py", line 21, in create_netbox_interface
    r = task.run(task=networking.napalm_get, getters=["interfaces"])
  File "/home/neoll/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/core/task.py", line 147, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: <function napalm_get at 0x7f3792ad4378> (failed)

![Screenshot_541](https://user-images.githubusercontent.com/20502851/69053439-76fde680-0a1a-11ea-9c39-f2fecb9f7a3a.png)

**Comment by hrtrd** [comment]
https://pastebin.com/TBgSZDaK

**Comment by dnmel** [comment]
the same issue (

**Comment by rickdonato** [comment]
Are you still having issues?
