### ISSUE TITLE
Can't make this work

### ISSUE THREAD

**Issue by nilldot** [rickdonato/nornir-napalm-netbox-demo#3]
Followed the https://www.packetflow.co.uk/how-to-build-a-network-automation-stack-with-nornir-napalm-and-netbox/ till #examples section.

Whatever I do, I can't make scripts/helpers.py or scripts/create_interfaces.py work with logs below. The way I see it it's either issue with Nornir Netbox plugin, or I misunderstand edits in scripts/helpers.py section #Although my understanding there I don;'t need to change anything, as changes are there already from the pull.

Any advise guys ?
Thanks!

#nornir.log
2020-01-12 23:15:07,471 - nornir.core.deserializer.configuration -    ERROR - _resolve_import_from_string() - Failed to import 'helpers.adapt_user_password'
Traceback (most recent call last):
  File "/root/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 217, in _resolve_import_from_string
    module = importlib.import_module(module_name)
  File "/root/nornir-napalm-netbox-demo/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/nornir-napalm-netbox-demo/scripts/helpers.py", line 22, in <module>
    nr = InitNornir(config_file="./config.yaml")
  File "/root/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/init_nornir.py", line 78, in InitNornir
    **conf.inventory.options,
  File "/root/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/core/deserializer/inventory.py", line 151, in deserialize
    transform_function_options=transform_function_options,
  File "/root/nornir-napalm-netbox-demo/venv/lib/python3.6/site-packages/nornir/core/inventory.py", line 414, in __init__
    transform_function(h, **transform_function_options)
  File "/root/nornir-napalm-netbox-demo/scripts/helpers.py", line 15, in adapt_user_password
    host.username = creds[f"{host}"]["username"]
KeyError: 'switch-01'

**Comment by rickdonato** [comment]
Is this now resolved?

**Comment by nilldot** [comment]
Hi,
Sadly no. We upgraded our https://phpipam.net and cancelled the netbox
project since.
Thanks for checking!

Regards,
Aleksandr

**Comment by ndom91** [comment]
Yeah I"m having the same issue. It can't find the transformer function under 'helpers.adapt_user_password' :/
